# Generated by Django 6.0.3 on 2026-03-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('commercial', 'Commercial'), ('land', 'Land')], max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area_sqft', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('carpet_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor_no', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, default='Pune', max_length=100)),
                ('locality', models.CharField(db_index=True, max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/main/%Y/%m/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('virtual_tour_url', models.URLField(blank=True, null=True)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='properties/floorplans/%Y/%m/')),
                ('builder_name', models.CharField(blank=True, max_length=200)),
                ('builder_logo', models.ImageField(blank=True, null=True, upload_to='builders/logos/')),
                ('rera_number', models.CharField(blank=True, max_length=50, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title (max 70 chars)', max_length=70)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description (max 160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_urgent_sale', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'status'], name='properties__city_eb43d5_idx'), models.Index(fields=['price', 'status'], name='properties__price_968017_idx'), models.Index(fields=['area_sqft', 'status'], name='properties__area_sq_779360_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='SEO alt text', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
