# Generated by Django 6.0.3 on 2026-04-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='locality',
        ),
        migrations.AddField(
            model_name='property',
            name='sublocation_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='rera_number',
            field=models.CharField(blank=True, default='A041262504685', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_fk', to='properties.city'),
        ),
        migrations.CreateModel(
            name='Sublocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='properties.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='sublocation_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_fk', to='properties.sublocation'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city_fk', 'status'], name='properties__city_fk_40256b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['sublocation_fk', 'status'], name='properties__subloca_87a48b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sublocation',
            unique_together={('city', 'name')},
        ),
    ]
