# Generated by Django 6.0.3 on 2026-04-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_city_remove_property_locality_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sublocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='sublocation',
            unique_together={('city', 'slug')},
        ),
    ]
