# Generated by Django 6.0.3 on 2026-04-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_sublocation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties__city_fk_40256b_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__subloca_87a48b_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__city_id_173494_idx',
            old_name='properties__city_eb43d5_idx',
        ),
        migrations.AddField(
            model_name='property',
            name='sublocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.sublocation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.city'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['sublocation', 'status'], name='properties__subloca_ff3046_idx'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='city_fk',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sublocation_fk',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sublocation_name',
        ),
    ]
