# Generated by Django 6.0.3 on 2026-04-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_properties__city_fk_40256b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('logo', models.ImageField(upload_to='builders/logos/')),
                ('description', models.TextField(blank=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.builder'),
        ),
        migrations.CreateModel(
            name='PropertyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2BHK Type A', max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('carpet_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='properties/configurations/%Y/%m/')),
                ('is_available', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='properties.property')),
            ],
        ),
    ]
