# Generated by Django 6.0.3 on 2026-04-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_builder_property_builder_propertyconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hide_price',
            field=models.BooleanField(default=False, help_text="Show 'Price on Request' instead of the actual price"),
        ),
        migrations.AddField(
            model_name='propertyconfiguration',
            name='hide_price',
            field=models.BooleanField(default=False),
        ),
    ]
