# Generated by Django 6.0.3 on 2026-04-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_hide_price_propertyconfiguration_hide_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_display',
            field=models.CharField(blank=True, help_text='Custom price display (e.g. 1.1cr - 1.5cr). If empty, numerical price will be shown.', max_length=100),
        ),
        migrations.AddField(
            model_name='propertyconfiguration',
            name='price_display',
            field=models.CharField(blank=True, help_text='e.g. 1.1cr - 1.5cr', max_length=100),
        ),
    ]
